# base_template.rb

run "echo TODO > README"

# Setup and install any gems we want to use

if yes?("Setup will_paginate? (yes/no)")
  gem 'mislav-will_paginate', :lib => 'will_paginate', :source => 'http://gems.github.com'
end

# Setup and use any plugins we want to use

if yes?("Would you like to use the Hoptoad notifier plugin? (yes/no)")
  plugin 'hoptoad_notifier', :git => 'git://github.com/thoughtbot/hoptoad_notifier.git'  
  hoptoad_api_key = ask('What is your Hoptoad API key?')

  gsub_file 'app/controllers/application_controller.rb', /(class ApplicationController.*)/, "\\1\n  include HoptoadNotifier::Catcher"
  
  initializer 'hoptoad.rb', <<-END
HoptoadNotifier.configure do |config|
  config.api_key = '#{hoptoad_api_key}'
end
END
end

if yes?("Niftify? (yes/no)")
  load_template "http://github.com/polly/rails_templates/raw/master/nifty_template.rb"
end

if yes?("Setup cucumber and shoulda? (yes/no)")
  load_template "http://github.com/polly/rails_templates/raw/master/test_template.rb"
end

if yes?("Setup our FormBuilder? (yes/no)")
  load_template "http://github.com/polly/rails_templates/raw/master/form_builder_template.rb"
  puts "+-------------------------------------------------------+"
  puts "| Usage:                                                |"
  puts "|   Use labeled_form_for instead of form_for            |"
  puts "+-------------------------------------------------------+"
end

# Edit files generated by rails

gsub_file 'app/controllers/application_controller.rb', /#\s*(filter_parameter_logging :password)/, '\1'


# Delete some files generated by rails

run "rm public/index.html"
run "rm public/favicon.ico"
run "rm public/robots.txt"


# Git specific setup
 
git :init

file ".gitignore", <<-END
.DS_Store
log/*.log
tmp/**/*
config/database.yml
db/*.sqlite3
END

run "touch tmp/.gitignore log/.gitignore vendor/.gitignore"
run "cp config/database.yml config/example_database.yml"

git :add => ".", :commit => "-m 'initial commit'"
