# Edit some of the files generated by rails

run "echo TODO > README"
gsub_file 'app/controllers/application_controller.rb', /#\s*(filter_parameter_logging :password)/, '\1'


# Delete some of the files generated by rails

run "rm public/index.html"
run "rm public/favicon.ico"
run "rm public/robots.txt"


# Git specific setup
 
git :init

file ".gitignore", <<-END
.DS_Store
log/*.log
tmp/**/*
config/database.yml
db/*.sqlite3
END

run "touch tmp/.gitignore log/.gitignore vendor/.gitignore"
run "cp config/database.yml config/example_database.yml"

git :add => ".", :commit => "-m 'initial commit'"